### ISSUE TITLE
Keys defined in test.sh are different from defined in tests  

### ISSUE THREAD

**Issue by artall64** [pumapayio/pumapay-token#3]
In `PumaPayPullPayment.test.js` you have constant:
```
CLIENT_ONE_PRIVATE_KEY= "0x....."
CLIENT_TWO_PRIVATE_KEY= "0x....."
CLIENT_THREE_PRIVATE_KEY= "0x....."
```
They are different from Ganache accounts defined in `scripts/test.sh` some of the tests probably failed because of that. Especially those that are related to signatures.

**Comment by kourtellosg** [comment]
I've made some changes regarding this on `v0.4.24` branch. I've updated the way we are starting the ganache-cli from `test.sh` script to use seed phrase instead of hardcoded accounts. @artall64 have a look as well and we can close this issue
