### ISSUE TITLE
Hardcoded ganache port in test files

### ISSUE THREAD

**Issue by artall64** [pumapayio/pumapay-token#4]
In `PumaPayPullPayment.test.js` address of HttpProvider is hardcoded:
`const web3API = new Web3(new Web3.providers.HttpProvider('http://localhost:7545'))`
If you launch Ganache using `scripts/test.sh` it starts it on `8545`

**Comment by kourtellosg** [comment]
This should also be fixed on `v0.4.24` branch. @artall64 have a look and we can close this as well
